global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor - Métricas dos containers Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Postgres Exporter - Métricas do banco de dados
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # StatsD Exporter - Métricas do Airflow
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
